#!/usr/bin/env python3
"""discovery-client-lite: Lightweight NVMe/TCP discovery connector.

Reads the discovery-client config directory, converts entries to
/etc/nvme/discovery.conf, and runs `nvme connect-all -p` to establish
persistent discovery connections. The kernel handles reconnection,
AEN, and keep-alive natively.

Commands:
  connect-all     Read config dir, write discovery.conf, run nvme connect-all -p
  disconnect-all  Clear discovery.conf, run nvme disconnect-all
"""

import argparse
import logging
import os
import subprocess
import sys
from pathlib import Path
from typing import List, Optional

log = logging.getLogger('discovery-client-lite')

DEFAULT_CONFIG_DIR = '/etc/discovery-client/discovery.d'
DISCOVERY_CONF = '/etc/nvme/discovery.conf'


def parse_config_line(line: str) -> Optional[str]:
    """Parse a discovery-client config line and return a discovery.conf line.

    Input format:  -t tcp -a ADDR -s PORT -q HOSTNQN -n SUBNQN [-S SECRET] [-C CTRL_SECRET] [-I HOSTID] [-l CTRL_LOSS_TMO]
    Output format: -t tcp -a ADDR -s PORT [-q HOSTNQN] [-S SECRET] [-C CTRL_SECRET] [-I HOSTID] [-l CTRL_LOSS_TMO]
    """
    line = line.strip()
    if not line or line.startswith('#'):
        return None

    tokens = line.split()
    traddr = port = hostnqn = subnqn = secret = ctrl_secret = hostid = ''
    ctrl_loss_tmo = None
    transport = 'tcp'
    i = 0
    while i < len(tokens):
        if tokens[i] == '-a' and i + 1 < len(tokens):
            traddr = tokens[i + 1]
            i += 2
        elif tokens[i] == '-s' and i + 1 < len(tokens):
            port = tokens[i + 1]
            i += 2
        elif tokens[i] == '-q' and i + 1 < len(tokens):
            hostnqn = tokens[i + 1]
            i += 2
        elif tokens[i] == '-n' and i + 1 < len(tokens):
            subnqn = tokens[i + 1]
            i += 2
        elif tokens[i] in ('-w', '-S') and i + 1 < len(tokens):
            secret = tokens[i + 1]
            i += 2
        elif tokens[i] == '-C' and i + 1 < len(tokens):
            ctrl_secret = tokens[i + 1]
            i += 2
        elif tokens[i] in ('-I', '--hostid') and i + 1 < len(tokens):
            hostid = tokens[i + 1]
            i += 2
        elif tokens[i] == '-l' and i + 1 < len(tokens):
            try:
                ctrl_loss_tmo = int(tokens[i + 1])
            except ValueError:
                log.warning('Invalid ctrl_loss_tmo value: %s', tokens[i + 1])
            i += 2
        elif tokens[i] == '-t' and i + 1 < len(tokens):
            transport = tokens[i + 1]
            i += 2
        else:
            i += 1

    if not traddr:
        return None

    # Always strip embedded port from traddr (e.g., "10.0.0.1:8009")
    if ':' in traddr:
        addr_part, _, maybe_port = traddr.rpartition(':')
        if maybe_port.isdigit():
            traddr = addr_part
            if not port:
                port = maybe_port

    port = port or '8009'

    # Build discovery.conf line — include -p for persistent connections
    parts = [f'-t {transport}', f'-a {traddr}', f'-s {port}', '-p']
    if hostnqn:
        parts.append(f'-q {hostnqn}')
    if secret:
        parts.append(f'-S {secret}')
    if ctrl_secret:
        parts.append(f'-C {ctrl_secret}')
    if hostid:
        parts.append(f'-I {hostid}')
    if ctrl_loss_tmo is not None:
        parts.append(f'-l {ctrl_loss_tmo}')
    return ' '.join(parts)


def read_config_dir(config_dir: str) -> List[str]:
    """Read all config files and return discovery.conf lines."""
    lines = []
    config_path = Path(config_dir)
    if not config_path.is_dir():
        log.warning('Config directory does not exist: %s', config_dir)
        return lines

    for f in sorted(config_path.iterdir()):
        if not f.is_file():
            continue
        try:
            for raw_line in f.read_text().splitlines():
                conf_line = parse_config_line(raw_line)
                if conf_line:
                    lines.append(conf_line)
        except OSError as e:
            log.warning('Failed to read config file %s: %s', f, e)

    return lines


def write_discovery_conf(lines: List[str]):
    """Write lines to /etc/nvme/discovery.conf."""
    os.makedirs(os.path.dirname(DISCOVERY_CONF), exist_ok=True)
    with open(DISCOVERY_CONF, 'w') as f:
        f.write('# Generated by discovery-client-lite\n')
        for line in lines:
            f.write(line + '\n')
    log.info('Wrote %d entries to %s', len(lines), DISCOVERY_CONF)


def clear_discovery_conf():
    """Clear /etc/nvme/discovery.conf."""
    try:
        with open(DISCOVERY_CONF, 'w') as f:
            f.write('')
        log.info('Cleared %s', DISCOVERY_CONF)
    except OSError as e:
        log.warning('Failed to clear %s: %s', DISCOVERY_CONF, e)


def run_nvme_connect_all():
    """Run nvme connect-all (reads /etc/nvme/discovery.conf)."""
    cmd = ['nvme', 'connect-all']
    log.info('Running: %s', ' '.join(cmd))
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.stdout.strip():
        log.info('nvme connect-all stdout: %s', result.stdout.strip())
    if result.stderr.strip():
        log.info('nvme connect-all stderr: %s', result.stderr.strip())
    if result.returncode != 0:
        log.error('nvme connect-all failed (rc=%d)', result.returncode)
        return False
    return True


def run_nvme_disconnect_all():
    """Run nvme disconnect-all."""
    cmd = ['nvme', 'disconnect-all']
    log.info('Running: %s', ' '.join(cmd))
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        log.error('nvme disconnect-all failed (rc=%d): %s',
                  result.returncode, result.stderr.strip())
        return False
    if result.stdout.strip():
        log.info('nvme disconnect-all output: %s', result.stdout.strip())
    return True


def cmd_connect_all(args):
    """Read config, write discovery.conf, run nvme connect-all -p."""
    config_dir = args.config_dir
    lines = read_config_dir(config_dir)
    if not lines:
        log.warning('No discovery endpoints found in %s', config_dir)
        return 0

    write_discovery_conf(lines)

    if not run_nvme_connect_all():
        return 1
    return 0


def cmd_disconnect_all(args):
    """Clear discovery.conf and run nvme disconnect-all."""
    clear_discovery_conf()

    if not run_nvme_disconnect_all():
        return 1
    return 0


def main():
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s %(name)s %(levelname)s %(message)s',
    )

    parser = argparse.ArgumentParser(
        description='Lightweight NVMe/TCP discovery connector',
    )
    sub = parser.add_subparsers(dest='command')
    sub.required = True

    ca_p = sub.add_parser(
        'connect-all',
        help='Read config dir, write discovery.conf, run nvme connect-all -p',
    )
    ca_p.add_argument(
        '--config-dir', default=DEFAULT_CONFIG_DIR,
        help=f'Discovery config directory (default: {DEFAULT_CONFIG_DIR})',
    )

    sub.add_parser(
        'disconnect-all',
        help='Clear discovery.conf and run nvme disconnect-all',
    )

    args = parser.parse_args()

    if args.command == 'connect-all':
        sys.exit(cmd_connect_all(args))
    elif args.command == 'disconnect-all':
        sys.exit(cmd_disconnect_all(args))


if __name__ == '__main__':
    main()
