# Copyright 2016--2022 Lightbits Labs Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# you may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ifneq ("$(wildcard /.inside-lb-build)","")
include $(WORKSPACE_TOP)/common/Makefile.env
endif

DEFAULT_DOCKER_REGISTRY := pulp-registry.lab.lightbitslabs.com
DOCKER_REGISTRY := $(or $(DOCKER_REGISTRY),$(DEFAULT_DOCKER_REGISTRY))

BUILD_FLAGS := DOCKER_REGISTRY=$(DOCKER_REGISTRY) \
    LIGHTOS_VERSION=$(LIGHTOS_VERSION)

build-image:
	$(BUILD_FLAGS) $(MAKE) build-image

push-image:
	$(BUILD_FLAGS) $(MAKE) push-image

build-image-ubi9:
	$(BUILD_FLAGS) $(MAKE) build-image-ubi9

push-image-ubi9:
	$(BUILD_FLAGS) $(MAKE) push-image-ubi9

discovery-rpms:
	$(BUILD_FLAGS) $(MAKE) -f Makefile discovery-rpms

# The builder image carries Go and the packaging tools; it is defined in this
# repo so it can be built and used without the internal build system.
BUILD_IMG_TAG := discovery-client-builder:$(shell md5sum env/build/Dockerfile | awk '{print $$1}')
MOUNT_ROOT := $(if $(WORKSPACE_TOP),$(WORKSPACE_TOP),$(CURDIR))

CONTAINER_RUN = docker run --rm \
	-v $(MOUNT_ROOT):$(MOUNT_ROOT) \
	-w $(CURDIR) \
	--user $(shell id -u):$(shell id -g) \
	$(BUILD_IMG_TAG)

.PHONY: build-builder-image
build-builder-image: env/build/Dockerfile
	docker build -q -f env/build/Dockerfile -t $(BUILD_IMG_TAG) . >/dev/null

# component-tool is part of the internal build system and is deliberately not in
# the builder image, so resolve the store path out here and pass it in.
DC_STORE = $(shell component-tool localpath --repo=discovery-client --type=$(BUILD_TYPE) discovery-client 2>/dev/null)
CLIENT_BIN_ARG = $(if $(DC_STORE),CLIENT_BIN=$(DC_STORE)/usr/bin/discovery-client,)

.PHONY: discovery-binary
discovery-binary: build-builder-image
	$(CONTAINER_RUN) $(MAKE) -f Makefile build/discovery-client

discovery-packages-%: build-builder-image
	@echo "Building discovery packages for $*"
	$(CONTAINER_RUN) $(MAKE) -f Makefile discovery-packages-$* $(BUILD_FLAGS) $(CLIENT_BIN_ARG)
